from sqlalchemy.orm import Session
from sqlalchemy import text

HARDWARE_SPECS = [
    {
        "system_name": "Mac Mini M4",
        "cpu_model": "Apple M4",
        "gpu_model": None,
        "igpu_model": "Apple M4 GPU (10-core)",
        "system_ram_gb": 16,
        "vram_gb": None,
        "memory_type": "Unified",
        "max_memory_gb": 32,
        "memory_bandwidth_gbs": 100.00,
        "tdp_watts": 15,
        "msrp_usd": 599.00,
        "release_year": 2024,
        "form_factor": "mini_pc",
    },
    {
        "system_name": "Mac Mini M4 Pro",
        "cpu_model": "Apple M4 Pro",
        "gpu_model": None,
        "igpu_model": "Apple M4 Pro GPU (20-core)",
        "system_ram_gb": 24,
        "vram_gb": None,
        "memory_type": "Unified",
        "max_memory_gb": 64,
        "memory_bandwidth_gbs": 273.00,
        "tdp_watts": 30,
        "msrp_usd": 1399.00,
        "release_year": 2024,
        "form_factor": "mini_pc",
    },
    {
        "system_name": "Mac Mini M4 Max",
        "cpu_model": "Apple M4 Max",
        "gpu_model": None,
        "igpu_model": "Apple M4 Max GPU (40-core)",
        "system_ram_gb": 64,
        "vram_gb": None,
        "memory_type": "Unified",
        "max_memory_gb": 128,
        "memory_bandwidth_gbs": 546.00,
        "tdp_watts": 40,
        "msrp_usd": 2999.00,
        "release_year": 2024,
        "form_factor": "mini_pc",
    },
    {
        "system_name": "Minisforum UM790 Pro",
        "cpu_model": "AMD Ryzen 9 7940HS",
        "gpu_model": None,
        "igpu_model": "AMD Radeon 780M",
        "system_ram_gb": 32,
        "vram_gb": None,
        "memory_type": "DDR5",
        "max_memory_gb": 64,
        "memory_bandwidth_gbs": 51.20,
        "tdp_watts": 54,
        "msrp_usd": 550.00,
        "release_year": 2023,
        "form_factor": "mini_pc",
    },
    {
        "system_name": "Minisforum MS-01",
        "cpu_model": "Intel Core i9-13900H",
        "gpu_model": None,
        "igpu_model": "Intel Iris Xe",
        "system_ram_gb": 64,
        "vram_gb": None,
        "memory_type": "DDR5",
        "max_memory_gb": 64,
        "memory_bandwidth_gbs": 76.80,
        "tdp_watts": 45,
        "msrp_usd": 850.00,
        "release_year": 2024,
        "form_factor": "mini_pc",
    },
    {
        "system_name": "Beelink SER8",
        "cpu_model": "AMD Ryzen 8945HS",
        "gpu_model": None,
        "igpu_model": "AMD Radeon 780M",
        "system_ram_gb": 32,
        "vram_gb": None,
        "memory_type": "DDR5",
        "max_memory_gb": 64,
        "memory_bandwidth_gbs": 51.20,
        "tdp_watts": 54,
        "msrp_usd": 450.00,
        "release_year": 2024,
        "form_factor": "mini_pc",
    },
    {
        "system_name": "Intel NUC 14 Pro",
        "cpu_model": "Intel Core Ultra 7 155H",
        "gpu_model": None,
        "igpu_model": "Intel Arc Graphics",
        "system_ram_gb": 32,
        "vram_gb": None,
        "memory_type": "DDR5",
        "max_memory_gb": 64,
        "memory_bandwidth_gbs": 76.80,
        "tdp_watts": 28,
        "msrp_usd": 600.00,
        "release_year": 2024,
        "form_factor": "nuc",
    },
    {
        "system_name": "NVIDIA Jetson AGX Orin",
        "cpu_model": "ARM Cortex-A78AE (12-core)",
        "gpu_model": "NVIDIA Ampere (2048 CUDA cores)",
        "igpu_model": None,
        "system_ram_gb": 64,
        "vram_gb": None,
        "memory_type": "LPDDR5",
        "max_memory_gb": 64,
        "memory_bandwidth_gbs": 204.00,
        "tdp_watts": 60,
        "msrp_usd": 1999.00,
        "release_year": 2023,
        "form_factor": "sbc",
    },
    {
        "system_name": "Framework 16",
        "cpu_model": "AMD Ryzen 7 7840HS",
        "gpu_model": None,
        "igpu_model": "AMD Radeon 780M",
        "system_ram_gb": 32,
        "vram_gb": None,
        "memory_type": "DDR5",
        "max_memory_gb": 64,
        "memory_bandwidth_gbs": 51.20,
        "tdp_watts": 54,
        "msrp_usd": 1400.00,
        "release_year": 2024,
        "form_factor": "laptop",
    },
    {
        "system_name": "Raspberry Pi 5",
        "cpu_model": "Broadcom BCM2712 (Cortex-A76)",
        "gpu_model": None,
        "igpu_model": "VideoCore VII",
        "system_ram_gb": 8,
        "vram_gb": None,
        "memory_type": "LPDDR4X",
        "max_memory_gb": 8,
        "memory_bandwidth_gbs": 34.00,
        "tdp_watts": 12,
        "msrp_usd": 80.00,
        "release_year": 2023,
        "form_factor": "sbc",
    },
]

MODEL_QUALITY = [
    {"model_family": "Llama-3", "model_variant": "Llama-3-8B-Instruct", "params_b": 8.0, "mmlu_score": 68.4, "lmsys_elo": None, "source_url": "https://huggingface.co/meta-llama/Meta-Llama-3-8B"},
    {"model_family": "Llama-3", "model_variant": "Llama-3-70B-Instruct", "params_b": 70.0, "mmlu_score": 82.0, "lmsys_elo": None, "source_url": "https://huggingface.co/meta-llama/Meta-Llama-3-70B"},
    {"model_family": "Mistral", "model_variant": "Mistral-7B-Instruct-v0.2", "params_b": 7.0, "mmlu_score": 62.5, "lmsys_elo": None, "source_url": "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2"},
    {"model_family": "Gemma-2", "model_variant": "Gemma-2-9B-Instruct", "params_b": 9.0, "mmlu_score": 71.3, "lmsys_elo": None, "source_url": "https://huggingface.co/google/gemma-2-9b"},
    {"model_family": "Phi-3", "model_variant": "Phi-3-mini-4k-instruct", "params_b": 3.8, "mmlu_score": 68.8, "lmsys_elo": None, "source_url": "https://huggingface.co/microsoft/Phi-3-mini-4k-instruct"},
    {"model_family": "Qwen2", "model_variant": "Qwen2-7B-Instruct", "params_b": 7.0, "mmlu_score": 70.3, "lmsys_elo": None, "source_url": "https://huggingface.co/Qwen/Qwen2-7B-Instruct"},
    {"model_family": "Qwen2.5", "model_variant": "Qwen2.5-72B-Instruct", "params_b": 72.0, "mmlu_score": 85.3, "lmsys_elo": None, "source_url": "https://huggingface.co/Qwen/Qwen2.5-72B-Instruct"},
]

SAMPLE_BENCHMARKS = [
    {
        "cpu_model": "Apple M4 Pro",
        "cpu_cores": 14,
        "cpu_threads": 14,
        "gpu_model": None,
        "igpu_model": "Apple M4 Pro GPU (20-core)",
        "total_ram_gb": 24,
        "vram_gb": None,
        "memory_type": "Unified",
        "memory_bandwidth_gbs": 273.00,
        "system_type": "Mac Mini M4 Pro",
        "hardware_price_usd": 1399.00,
        "os": "macOS 15.2",
        "inference_engine": "MLX",
        "engine_version": "0.21.0",
        "model_name": "Llama-3-8B-Instruct",
        "model_params_b": 8.0,
        "quantization": "Q4_K_M",
        "tokens_per_second": 52.3,
        "time_to_first_token": 0.18,
        "prompt_tokens": 245,
        "completion_tokens": 512,
        "test_duration_secs": 14.5,
        "model_quality_score": 68.4,
        "quality_source": "mmlu",
        "fingerprint": "abc123def456",
        "client_version": "0.1.0",
    },
    {
        "cpu_model": "Apple M4",
        "cpu_cores": 10,
        "cpu_threads": 10,
        "gpu_model": None,
        "igpu_model": "Apple M4 GPU (10-core)",
        "total_ram_gb": 16,
        "vram_gb": None,
        "memory_type": "Unified",
        "memory_bandwidth_gbs": 100.00,
        "system_type": "Mac Mini M4",
        "hardware_price_usd": 599.00,
        "os": "macOS 15.2",
        "inference_engine": "MLX",
        "engine_version": "0.21.0",
        "model_name": "Llama-3-8B-Instruct",
        "model_params_b": 8.0,
        "quantization": "Q4_K_M",
        "tokens_per_second": 28.7,
        "time_to_first_token": 0.32,
        "prompt_tokens": 245,
        "completion_tokens": 512,
        "test_duration_secs": 26.3,
        "model_quality_score": 68.4,
        "quality_source": "mmlu",
        "fingerprint": "xyz789ghi012",
        "client_version": "0.1.0",
    },
    {
        "cpu_model": "AMD Ryzen 9 7940HS",
        "cpu_cores": 8,
        "cpu_threads": 16,
        "gpu_model": None,
        "igpu_model": "AMD Radeon 780M",
        "total_ram_gb": 32,
        "vram_gb": None,
        "memory_type": "DDR5",
        "memory_bandwidth_gbs": 51.20,
        "system_type": "Minisforum UM790 Pro",
        "hardware_price_usd": 550.00,
        "os": "Ubuntu 24.04",
        "inference_engine": "ollama",
        "engine_version": "0.3.12",
        "model_name": "Llama-3-8B-Instruct",
        "model_params_b": 8.0,
        "quantization": "Q4_K_M",
        "tokens_per_second": 18.4,
        "time_to_first_token": 0.45,
        "prompt_tokens": 245,
        "completion_tokens": 512,
        "test_duration_secs": 41.1,
        "model_quality_score": 68.4,
        "quality_source": "mmlu",
        "fingerprint": "um790pro_001",
        "client_version": "0.1.0",
    },
    {
        "cpu_model": "Apple M4 Max",
        "cpu_cores": 16,
        "cpu_threads": 16,
        "gpu_model": None,
        "igpu_model": "Apple M4 Max GPU (40-core)",
        "total_ram_gb": 64,
        "vram_gb": None,
        "memory_type": "Unified",
        "memory_bandwidth_gbs": 546.00,
        "system_type": "Mac Mini M4 Max",
        "hardware_price_usd": 2999.00,
        "os": "macOS 15.2",
        "inference_engine": "MLX",
        "engine_version": "0.21.0",
        "model_name": "Qwen2.5-72B-Instruct",
        "model_params_b": 72.0,
        "quantization": "Q4_K_M",
        "tokens_per_second": 22.1,
        "time_to_first_token": 1.82,
        "prompt_tokens": 245,
        "completion_tokens": 512,
        "test_duration_secs": 34.9,
        "model_quality_score": 85.3,
        "quality_source": "mmlu",
        "fingerprint": "m4max_001",
        "client_version": "0.1.0",
    },
    {
        "cpu_model": "Intel Core i9-13900H",
        "cpu_cores": 14,
        "cpu_threads": 20,
        "gpu_model": None,
        "igpu_model": "Intel Iris Xe",
        "total_ram_gb": 64,
        "vram_gb": None,
        "memory_type": "DDR5",
        "memory_bandwidth_gbs": 76.80,
        "system_type": "Minisforum MS-01",
        "hardware_price_usd": 850.00,
        "os": "Ubuntu 24.04",
        "inference_engine": "ollama",
        "engine_version": "0.3.12",
        "model_name": "Mistral-7B-Instruct-v0.2",
        "model_params_b": 7.0,
        "quantization": "Q8_0",
        "tokens_per_second": 14.2,
        "time_to_first_token": 0.55,
        "prompt_tokens": 245,
        "completion_tokens": 512,
        "test_duration_secs": 53.2,
        "model_quality_score": 62.5,
        "quality_source": "mmlu",
        "fingerprint": "ms01_001",
        "client_version": "0.1.0",
    },
    {
        "cpu_model": "AMD Ryzen 8945HS",
        "cpu_cores": 8,
        "cpu_threads": 16,
        "gpu_model": None,
        "igpu_model": "AMD Radeon 780M",
        "total_ram_gb": 32,
        "vram_gb": None,
        "memory_type": "DDR5",
        "memory_bandwidth_gbs": 51.20,
        "system_type": "Beelink SER8",
        "hardware_price_usd": 450.00,
        "os": "Windows 11",
        "inference_engine": "ollama",
        "engine_version": "0.3.12",
        "model_name": "Phi-3-mini-4k-instruct",
        "model_params_b": 3.8,
        "quantization": "Q4_K_M",
        "tokens_per_second": 32.6,
        "time_to_first_token": 0.22,
        "prompt_tokens": 245,
        "completion_tokens": 512,
        "test_duration_secs": 23.5,
        "model_quality_score": 68.8,
        "quality_source": "mmlu",
        "fingerprint": "ser8_001",
        "client_version": "0.1.0",
    },
    {
        "cpu_model": "ARM Cortex-A78AE (12-core)",
        "cpu_cores": 12,
        "cpu_threads": 12,
        "gpu_model": "NVIDIA Ampere (2048 CUDA cores)",
        "igpu_model": None,
        "total_ram_gb": 64,
        "vram_gb": None,
        "memory_type": "LPDDR5",
        "memory_bandwidth_gbs": 204.00,
        "system_type": "NVIDIA Jetson AGX Orin",
        "hardware_price_usd": 1999.00,
        "os": "JetPack 6.0",
        "inference_engine": "llama.cpp",
        "engine_version": "b3100",
        "model_name": "Llama-3-8B-Instruct",
        "model_params_b": 8.0,
        "quantization": "Q4_K_M",
        "tokens_per_second": 38.9,
        "time_to_first_token": 0.28,
        "prompt_tokens": 245,
        "completion_tokens": 512,
        "test_duration_secs": 19.4,
        "model_quality_score": 68.4,
        "quality_source": "mmlu",
        "fingerprint": "jetson_001",
        "client_version": "0.1.0",
    },
    {
        "cpu_model": "Broadcom BCM2712 (Cortex-A76)",
        "cpu_cores": 4,
        "cpu_threads": 4,
        "gpu_model": None,
        "igpu_model": "VideoCore VII",
        "total_ram_gb": 8,
        "vram_gb": None,
        "memory_type": "LPDDR4X",
        "memory_bandwidth_gbs": 34.00,
        "system_type": "Raspberry Pi 5",
        "hardware_price_usd": 80.00,
        "os": "Raspberry Pi OS 12",
        "inference_engine": "llama.cpp",
        "engine_version": "b3100",
        "model_name": "Phi-3-mini-4k-instruct",
        "model_params_b": 3.8,
        "quantization": "Q4_K_M",
        "tokens_per_second": 4.2,
        "time_to_first_token": 2.10,
        "prompt_tokens": 245,
        "completion_tokens": 512,
        "test_duration_secs": 182.0,
        "model_quality_score": 68.8,
        "quality_source": "mmlu",
        "fingerprint": "rpi5_001",
        "client_version": "0.1.0",
    },
]


ARENA_MODELS = [
    {
        "model_id": "openai/gpt-5.5",
        "display_name": "GPT-5.5",
        "provider": "OpenAI",
        "modality": "multimodal",
        "task_tags": ["overall", "agentic_coding", "long_running", "reasoning"],
        "arena_rank": 1,
        "arena_score": 1462.0,
        "intelligence_index": 73.0,
        "output_speed_tps": 88.0,
        "cost_per_million_tokens": 17.50,
        "context_window": 400000,
        "strengths": ["frontier reasoning", "tool use", "coding agents"],
        "source_name": "LMArena / Artificial Analysis references",
        "source_url": "https://lmarena.ai/leaderboard",
    },
    {
        "model_id": "anthropic/claude-opus-4.5",
        "display_name": "Claude Opus 4.5",
        "provider": "Anthropic",
        "modality": "text",
        "task_tags": ["overall", "agentic_coding", "long_running", "writing"],
        "arena_rank": 2,
        "arena_score": 1454.0,
        "intelligence_index": 72.0,
        "output_speed_tps": 64.0,
        "cost_per_million_tokens": 35.00,
        "context_window": 200000,
        "strengths": ["long-horizon coding", "planning", "review quality"],
        "source_name": "LMArena / SWE-bench style references",
        "source_url": "https://swebench.com/",
    },
    {
        "model_id": "xai/grok-4.1",
        "display_name": "Grok 4.1",
        "provider": "xAI",
        "modality": "multimodal",
        "task_tags": ["overall", "agentic_coding", "research", "reasoning"],
        "arena_rank": 3,
        "arena_score": 1447.0,
        "intelligence_index": 70.0,
        "output_speed_tps": 112.0,
        "cost_per_million_tokens": 12.00,
        "context_window": 256000,
        "strengths": ["fresh knowledge workflows", "fast iteration", "tool-heavy research"],
        "source_name": "LMArena / Artificial Analysis references",
        "source_url": "https://artificialanalysis.ai/",
    },
    {
        "model_id": "google/gemini-3-pro",
        "display_name": "Gemini 3 Pro",
        "provider": "Google",
        "modality": "multimodal",
        "task_tags": ["overall", "image", "long_running", "reasoning"],
        "arena_rank": 4,
        "arena_score": 1438.0,
        "intelligence_index": 69.0,
        "output_speed_tps": 96.0,
        "cost_per_million_tokens": 10.00,
        "context_window": 1000000,
        "strengths": ["long context", "multimodal analysis", "document work"],
        "source_name": "Artificial Analysis / LiveBench references",
        "source_url": "https://livebench.ai/",
    },
    {
        "model_id": "openai/gpt-image-2",
        "display_name": "GPT Image 2",
        "provider": "OpenAI",
        "modality": "image",
        "task_tags": ["image", "creative", "design"],
        "arena_rank": 5,
        "arena_score": 1395.0,
        "intelligence_index": None,
        "output_speed_tps": None,
        "cost_per_million_tokens": None,
        "context_window": None,
        "strengths": ["prompt adherence", "text rendering", "iterative editing"],
        "source_name": "LMArena image arena reference",
        "source_url": "https://lmarena.ai/leaderboard/image",
    },
    {
        "model_id": "black-forest-labs/flux-2-pro",
        "display_name": "FLUX 2 Pro",
        "provider": "Black Forest Labs",
        "modality": "image",
        "task_tags": ["image", "creative", "design"],
        "arena_rank": 6,
        "arena_score": 1388.0,
        "intelligence_index": None,
        "output_speed_tps": None,
        "cost_per_million_tokens": None,
        "context_window": None,
        "strengths": ["photorealism", "style control", "commercial image workflows"],
        "source_name": "LMArena image arena reference",
        "source_url": "https://lmarena.ai/leaderboard/image",
    },
]


def seed_hardware_specs(session: Session):
    from app.models import HardwareSpec
    for spec in HARDWARE_SPECS:
        existing = session.query(HardwareSpec).filter_by(system_name=spec["system_name"]).first()
        if not existing:
            session.add(HardwareSpec(**spec))
    session.commit()


def seed_model_quality(session: Session):
    from app.models import ModelQuality
    for mq in MODEL_QUALITY:
        existing = session.query(ModelQuality).filter_by(
            model_family=mq["model_family"],
            model_variant=mq["model_variant"]
        ).first()
        if not existing:
            session.add(ModelQuality(**mq))
    session.commit()


def seed_benchmarks(session: Session):
    from app.models import Benchmark
    # Only seed if table is empty
    if session.query(Benchmark).count() == 0:
        for b in SAMPLE_BENCHMARKS:
            session.add(Benchmark(**b))
        session.commit()


def seed_arena_models(session: Session):
    from app.models import ArenaModel
    for model in ARENA_MODELS:
        existing = session.query(ArenaModel).filter_by(model_id=model["model_id"]).first()
        if not existing:
            session.add(ArenaModel(**model))
        else:
            for key, value in model.items():
                setattr(existing, key, value)
    session.commit()


def run_seed():
    from sqlalchemy import create_engine
    from sqlalchemy.orm import sessionmaker
    from app.config import settings
    from app.database import Base

    engine = create_engine(settings.database_url_sync)
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine)
    session = Session()
    try:
        seed_hardware_specs(session)
        seed_model_quality(session)
        seed_benchmarks(session)
        seed_arena_models(session)
        print("Seed data loaded successfully.")
    finally:
        session.close()
        engine.dispose()


if __name__ == "__main__":
    run_seed()
